#!/home/samhaug/anaconda2/bin/python

'''
==============================================================================

File Name : axisem3d_h5
Purpose : save axisem3d output as h5 files
Creation Date : 11-01-2018
Last Modified : Thu 11 Jan 2018 06:35:05 PM EST
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from os import listdir
import obspy


def make_traces():
    st_r = obspy.core.Stream()
    st_t = obspy.core.Stream()
    st_z = obspy.core.Stream()

    stat_files = listdir('stations')
    stat_list = open('STATIONS').readlines()

    for ii in stat_list:
        name = ii.strip().split()
        lat = float(name[2])
        lon = float(name[3])
        fname = '{}.{}.RTZ.ascii'.format(name[1],name[0])
        data = np.genfromtxt('stations/'+fname)

        tr_r = obspy.core.Trace()
        tr_t = obspy.core.Trace()
        tr_z = obspy.core.Trace()

        t = data[:,0]
        r = data[:,1]
        t = data[:,2]
        z = data[:,3]

        tr_r.stats.sampling_rate = len(data[:,0])/data[:,0].max()
        tr_t.stats.sampling_rate = len(data[:,0])/data[:,0].max()
        tr_z.stats.sampling_rate = len(data[:,0])/data[:,0].max()

        tr_r.stats.stla = lat
        tr_r.stats.stlo = lon
        tr_t.stats.stla = lat
        tr_t.stats.stlo = lon
        tr_z.stats.stla = lat
        tr_z.stats.stlo = lon

        st_r.append(tr_r)
        st_t.append(tr_t)
        st_z.append(tr_z)
    return st_r,st_t,st_z

def get_source_metadata(st_r,st_t,st_z):
    CMT = open('CMTSOLUTION').readlines()
    top = [int(ii) for ii in CMT[0].strip().split()[1:6]]
    sec = float(CMT[0].strip().split()[6])
    starttime = obspy.core.UTCDateTime(top[0],top[1],top[2],
                           top[3],top[4],sec)
    evla = float(CMT[4].strip().split()[-1])
    evlo = float(CMT[5].strip().split()[-1])

    for idx,tr in enumerate(st_r):
        st_r[idx].stats.starttime = starttime
        st_r[idx].stats.evla = evla
        st_r[idx].stats.evlo = evlo
        st_t[idx].stats.starttime = starttime
        st_t[idx].stats.evla = evla
        st_t[idx].stats.evlo = evlo
        st_z[idx].stats.starttime = starttime
        st_z[idx].stats.evla = evla
        st_z[idx].stats.evlo = evlo

    return st_r,st_t,st_z


print('Make traces')
st_r,st_t,st_z = make_traces()
print('Source metadata')
st_r,st_t,st_z = get_source_metadata(st_r,st_t,st_z)

print('Writing')
st_r.write('st_R.h5',format='H5')
st_t.write('st_T.h5',format='H5')
st_z.write('st_Z.h5',format='H5')





