#!/home/samhaug/anaconda2/bin/python

import obspy
import seispy
from sys import argv

def main():
    ref_st = obspy.read(argv[1])
    stn = obspy.read('*BHN.filtered')
    ste = obspy.read('*BHE.filtered')
    stz = obspy.read('*BHZ.filtered')

    for idx, ii in enumerate(stn):
        stn[idx].stats.evla = ref_st[0].stats.evla
        stn[idx].stats.evlo = ref_st[0].stats.evlo
        ste[idx].stats.evla = ref_st[0].stats.evla
        ste[idx].stats.evlo = ref_st[0].stats.evlo
        stz[idx].stats.evla = ref_st[0].stats.evla
        stz[idx].stats.evlo = ref_st[0].stats.evlo
        stn[idx].stats.stla = ref_st[0].stats.stla
        stn[idx].stats.stlo = ref_st[0].stats.stlo
        ste[idx].stats.stla = ref_st[0].stats.stla
        ste[idx].stats.stlo = ref_st[0].stats.stlo
        stz[idx].stats.stla = ref_st[0].stats.stla
        stz[idx].stats.stlo = ref_st[0].stats.stlo
        stz[idx].stats.o = 0
        ste[idx].stats.o = 0
        stn[idx].stats.o = 0
        stn[idx].stats.evdp = ref_st[0].stats.evdp
        ste[idx].stats.evdp = ref_st[0].stats.evdp
        stz[idx].stats.evdp = ref_st[0].stats.evdp

    stn = seispy.convert.set_gcarc(stn)
    ste = seispy.convert.set_gcarc(ste)
    stz = seispy.convert.set_gcarc(stz)

    try:
        l,q,t = seispy.data.rotate_phase(stz,stn,ste,['ScSScS'])
    except:
        print('WARNING: divide depth by 1000')
        for idx, ii in enumerate(stn):
            stn[idx].stats.evdp*=1./1000
            ste[idx].stats.evdp*=1./1000
            stz[idx].stats.evdp*=1./1000
        l,q,t = seispy.data.rotate_phase(stz,stn,ste,['ScSScS'])

    l.write('st_L.h5',format='H5')
    q.write('st_Q.h5',format='H5')
    t.write('st_T.h5',format='H5')
    stn.write('st_N.h5',format='H5')
    ste.write('st_E.h5',format='H5')
    stz.write('st_Z.h5',format='H5')
main()
